server:
  port: 8080

spring:
  application:
    name: ai-agent

  jackson:
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    root: INFO
    com.ELEC5620.aiagent: DEBUG
  file:
    name: logs/doctor-service.log
